// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoleBased.Infrastructure.Persistance;

#nullable disable

namespace RoleBased.Infrastructure.Migrations
{
    [DbContext(typeof(RoleBasedDbContext))]
    partial class RoleBasedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleBased.Model.LoginDB", b =>
                {
                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegNo");

                    b.ToTable("LoginDB");
                });

            modelBuilder.Entity("RoleBased.Model.StudentInfo", b =>
                {
                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DOB")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RegNo");

                    b.ToTable("StudentInfo");

                    b.HasData(
                        new
                        {
                            RegNo = "1",
                            Created = new DateTimeOffset(new DateTime(2023, 10, 2, 15, 56, 36, 481, DateTimeKind.Unspecified).AddTicks(1964), new TimeSpan(0, 6, 0, 0, 0)),
                            CreatedBy = "1",
                            DOB = new DateTimeOffset(new DateTime(2023, 10, 2, 15, 56, 36, 481, DateTimeKind.Unspecified).AddTicks(1937), new TimeSpan(0, 6, 0, 0, 0)),
                            Email = "rahat@gmail.com",
                            LastModified = new DateTimeOffset(new DateTime(2023, 10, 2, 15, 56, 36, 481, DateTimeKind.Unspecified).AddTicks(1966), new TimeSpan(0, 6, 0, 0, 0)),
                            Name = "Rahat Ahmed Tanjim",
                            PhoneNumber = "0198xxxxxx",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
